<div class="banner-grid">
    <a href="/celulares">
        <div class="item" style="background-image: url('<?php echo $this->getViewFileUrl('images/banner/banner-grade-1.jpeg'); ?>')"></div>
    </a>
    
    <a href="/celulares">
        <div class="item" style="background-image: url('<?php echo $this->getViewFileUrl('images/banner/banner-grade-1.jpeg'); ?>')"></div>
    </a>
    <a href="/celulares">
        <div class="item" style="background-image: url('<?php echo $this->getViewFileUrl('images/banner/banner-grade-1.jpeg'); ?>')"></div>
    </a>
    <a href="/celulares">
        <div class="item" style="background-image: url('<?php echo $this->getViewFileUrl('images/banner/banner-grade-1.jpeg'); ?>')"></div>
    </a>
</div>